### ISSUE TITLE
Doesn't work in my Safari browser (OS X 10.10.5)

### ISSUE THREAD

**Issue by benhj** [RoyCurtis/Flurry-WebGL#2]
Works fine in Chrome though.. Cheers!

"Flurry crashed; please visit http://get.webgl.org/ for more information."

**Comment by RoyCurtis** [comment]
Thanks for this report! Unfortunately I am unable to test in Safari. Can you please show me the contents of the Console, either pasted or [as a screenshot](http://i.imgur.com/RXVGmza.jpg)?

**Comment by benhj** [comment]
mainFlurry.js:26[Main] Setting up renderer...
RendererRenderer.js:87WebGL: INVALID_ENUM: disable: invalid capability
RendererRenderer.js:88WebGL: INVALID_ENUM: disable: invalid capability
RendererRenderer.js:89WebGL: INVALID_ENUM: enable: invalid capability
useShaderRenderer.js:172WebGL: INVALID_ENUM: createShader: invalid shader type
useShaderRenderer.js:176WebGL: INVALID_VALUE: shaderSource: no object or object deleted
useShaderRenderer.js:177WebGL: INVALID_VALUE: compileShader: no object or object deleted
useShaderRenderer.js:179WebGL: INVALID_VALUE: getShaderParameter: no object or object deleted
useShaderRenderer.js:180WebGL: INVALID_VALUE: getShaderInfoLog: no object or object deleted
Flurry-WebGL:136Error: null
(anonymous function)Flurry-WebGL:135

Perhaps I don't actually have the webgl plugin...

**Comment by spinwtf** [comment]
Can confirm this error still shows in 10.11.2 (beta) in Safari 9.

**Comment by RoyCurtis** [comment]
@benhj - I believe this is fixed. A technical explanation:

In the code, I was using `WebGLRenderingContext` on its own to reference GL constants. For example:

``` javascript
var gl   = this.gl,
    GLES = WebGLRenderingContext;

gl.blendEquation(GLES.FUNC_ADD);
gl.blendFunc(GLES.SRC_ALPHA, GLES.ONE_MINUS_SRC_ALPHA);
```

This works fine in Chrome and Firefox. However in later Safari, for some reason these constants are not available in the `WebGLRenderingContext` object unless prototyped. So instead, I have had to do this:

``` javascript
var gl   = this.gl;

gl.blendEquation(gl.FUNC_ADD);
gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
```

Many thanks to @spinnibbler and Scrogs63 for helping me test this, and to you for reporting it.
